package com.example.smileapp.smile;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Represents a smile that can be crying or laughing.
 */
@Entity
public class Smile {

  /**
   * Id property is autogenerated.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private Long id;

  /**
   * isCrying property initialized as a Boolean.
   */
  private Boolean isCrying;

  /**
   * isLaughing property initialized as a Boolean.
   */
  private Boolean isLaughing;

  public Smile() {
  }

  public Smile(final Boolean pIsCrying, final Boolean pIsLaughing) {
    this.isCrying = pIsCrying;
    this.isLaughing = pIsLaughing;
  }

  public void setCrying() {
    this.isCrying = true;
    this.isLaughing = false;
  }

  public void setLaughing() {
    this.isCrying = false;
    this.isLaughing = true;
  }

  public Boolean getCrying() {
    return this.isCrying;
  }

  public Boolean getLaughing() {
    return this.isLaughing;
  }

  public Long getId() {
    return id;
  }

  @Override
  public String toString() {
    return String.format("Smile[id=%d isCrying='%s' isLaughing='%s']", id, isCrying, isLaughing);
  }
}
